-- ============================================================
--  MEDBOOK INDIA — DATABASE SCHEMA
--  Phase 4: Bookings, Cancellations, Reschedules & Audit Log
--  Depends on: Phase 1 (users, patient_profiles)
--              Phase 2 (doctor_profiles, clinic_profiles)
--              Phase 3 (time_slots, schedule_rules)
--  Database: PostgreSQL 15+
--  Version: 1.0 — April 2026
-- ============================================================


-- ── ENUMS ────────────────────────────────────────────────────

-- Full lifecycle of a booking.
CREATE TYPE booking_status AS ENUM (
  'initiated',      -- patient started checkout, slot is locked (max 5 mins)
  'confirmed',      -- patient confirmed, slot is booked, notifications sent
  'completed',      -- appointment happened (marked by clinic or auto after slot time)
  'cancelled',      -- cancelled by patient, doctor, or clinic
  'rescheduled',    -- this booking was moved — a new booking was created
  'no_show'         -- patient did not attend and did not cancel
);

-- How the patient intends to pay.
CREATE TYPE payment_method AS ENUM (
  'pay_at_clinic',  -- cash or UPI at the clinic desk (default)
  'upi_online',     -- paid via GPay / PhonePe / Paytm before visit
  'card_online'     -- paid via debit/credit card before visit (Phase 2)
);

-- Status of an online payment (only relevant for upi_online / card_online).
CREATE TYPE payment_status AS ENUM (
  'not_applicable',  -- pay_at_clinic bookings
  'pending',         -- payment initiated, awaiting confirmation
  'paid',            -- payment confirmed by gateway
  'failed',          -- payment attempt failed
  'refunded'         -- payment reversed (after cancellation)
);

-- Who initiated a cancellation or reschedule.
CREATE TYPE action_initiator AS ENUM (
  'patient',
  'doctor',
  'clinic',
  'platform_admin',
  'system'           -- automated (e.g., doctor blocked dates cascade)
);

-- Reason categories for cancellation.
CREATE TYPE cancellation_reason AS ENUM (
  -- Patient-initiated reasons
  'patient_personal',
  'patient_recovered',
  'patient_found_another_doctor',
  'patient_cost_concern',
  -- Doctor-initiated reasons
  'doctor_unavailable',
  'doctor_emergency',
  'doctor_schedule_change',
  -- Clinic-initiated reasons
  'clinic_closed',
  'clinic_emergency',
  'clinic_doctor_left',
  -- System reasons
  'system_double_booking_error',
  'system_slot_expired',
  -- Other
  'other'
);

-- Every action on every booking is recorded with a type.
CREATE TYPE audit_action AS ENUM (
  'booking_initiated',
  'booking_confirmed',
  'booking_cancelled',
  'booking_rescheduled',
  'booking_completed',
  'booking_no_show',
  'slot_locked',
  'slot_lock_released',
  'payment_initiated',
  'payment_confirmed',
  'payment_failed',
  'payment_refunded',
  'notification_sent',
  'reminder_sent',
  'review_requested',
  'flag_raised',        -- admin flag raised on this booking
  'flag_resolved'
);


-- ── TABLE: bookings ───────────────────────────────────────────
-- The central booking record. One row per appointment.
-- Never deleted. Status changes are the only mutations allowed.
--
-- Booking ID format: We generate a human-readable booking reference
-- (e.g., MB-30841) separately in application code for display.
-- The UUID id is used internally for all joins and queries.

CREATE TABLE bookings (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Human-readable reference shown to patients (e.g., MB-30841).
  -- Generated by application code. Unique, NOT sequential (security).
  booking_reference     VARCHAR(20) NOT NULL UNIQUE,

  -- ── Core Relationships ─────────────────────────────────────
  -- The patient making this booking.
  patient_id            UUID NOT NULL REFERENCES patient_profiles(id)
                          ON DELETE RESTRICT,

  -- The doctor being booked.
  doctor_id             UUID NOT NULL REFERENCES doctor_profiles(id)
                          ON DELETE RESTRICT,

  -- The clinic/hospital where the appointment will happen.
  clinic_id             UUID NOT NULL REFERENCES clinic_profiles(id)
                          ON DELETE RESTRICT,

  -- The specific time slot being booked.
  -- ON DELETE RESTRICT: cannot delete a slot that has a booking.
  slot_id               UUID NOT NULL REFERENCES time_slots(id)
                          ON DELETE RESTRICT,

  -- ── Appointment Details ────────────────────────────────────
  -- Denormalised from time_slots for fast retrieval without joins.
  -- These values never change after booking is confirmed.
  appointment_date      DATE NOT NULL,
  appointment_start_at  TIMESTAMPTZ NOT NULL,
  appointment_end_at    TIMESTAMPTZ NOT NULL,

  -- ── Booking State ──────────────────────────────────────────
  status                booking_status NOT NULL DEFAULT 'initiated',

  -- ── Patient Input ──────────────────────────────────────────
  -- Optional reason for visit (patient-provided at booking time).
  -- Visible to doctor before appointment.
  reason_for_visit      TEXT,

  -- ── Payment ────────────────────────────────────────────────
  payment_method        payment_method NOT NULL DEFAULT 'pay_at_clinic',
  payment_status        payment_status NOT NULL DEFAULT 'not_applicable',

  -- Consultation fee at the time of booking (in paise).
  -- Stored here because fees can change. We need the historical value.
  fee_paise             INTEGER NOT NULL DEFAULT 0,

  -- Payment gateway transaction reference (Razorpay order/payment ID).
  -- NULL for pay_at_clinic bookings.
  payment_gateway_ref   VARCHAR(255),
  payment_confirmed_at  TIMESTAMPTZ,

  -- ── Completion Tracking ────────────────────────────────────
  -- When the clinic marked the patient as 'seen/done'.
  completed_at          TIMESTAMPTZ,
  completed_by          UUID REFERENCES users(id) ON DELETE SET NULL,

  -- ── No-Show Tracking ──────────────────────────────────────
  -- When the no-show was recorded (auto or manual by clinic).
  no_show_recorded_at   TIMESTAMPTZ,
  no_show_recorded_by   UUID REFERENCES users(id) ON DELETE SET NULL,

  -- ── Rescheduling Link ──────────────────────────────────────
  -- If this booking was rescheduled FROM another booking, link it.
  rescheduled_from_id   UUID REFERENCES bookings(id) ON DELETE SET NULL,

  -- If this booking was rescheduled TO a new booking, link it.
  rescheduled_to_id     UUID REFERENCES bookings(id) ON DELETE SET NULL,

  -- ── Review Tracking ────────────────────────────────────────
  -- Has the post-visit review WhatsApp been sent?
  review_requested_at   TIMESTAMPTZ,

  -- Has the patient left a review for this booking?
  review_id             UUID,  -- FK added after reviews table is created

  -- ── Admin Flags ────────────────────────────────────────────
  -- Automatically set TRUE if cancellation happened within 2 hours.
  is_flagged            BOOLEAN NOT NULL DEFAULT FALSE,
  flag_reason           TEXT,
  flagged_at            TIMESTAMPTZ,
  flag_resolved_at      TIMESTAMPTZ,
  flag_resolved_by      UUID REFERENCES users(id) ON DELETE SET NULL,

  -- ── Notifications ──────────────────────────────────────────
  -- Track notification status for debugging and audit.
  confirmation_sent_at  TIMESTAMPTZ,   -- WhatsApp/SMS on booking confirm
  reminder_24h_sent_at  TIMESTAMPTZ,   -- 24h before reminder
  reminder_2h_sent_at   TIMESTAMPTZ,   -- 2h before reminder

  -- ── Source Tracking ────────────────────────────────────────
  -- Which app/platform was used to make this booking?
  booking_source        VARCHAR(50) DEFAULT 'patient_app',
  -- e.g. 'patient_app', 'clinic_app', 'web', 'admin_panel'

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── INDEXES for bookings ──────────────────────────────────────
-- Patient's booking history (My Bookings screen).
CREATE INDEX idx_bookings_patient        ON bookings (patient_id, appointment_date DESC);

-- Doctor's appointment list (Today's Appointments screen).
CREATE INDEX idx_bookings_doctor_date    ON bookings (doctor_id, appointment_date);

-- Clinic's daily queue (Today's Queue screen).
CREATE INDEX idx_bookings_clinic_date    ON bookings (clinic_id, appointment_date);

-- Slot lookup (checking if a slot is already booked).
CREATE INDEX idx_bookings_slot_id        ON bookings (slot_id);

-- Admin: all flagged bookings.
CREATE INDEX idx_bookings_flagged        ON bookings (is_flagged, flagged_at)
  WHERE is_flagged = TRUE;

-- Status-based queries (find all confirmed bookings, etc.).
CREATE INDEX idx_bookings_status         ON bookings (status);

-- Reminder job: find confirmed bookings needing 24h reminder.
CREATE INDEX idx_bookings_reminder_24h   ON bookings (appointment_start_at, reminder_24h_sent_at)
  WHERE status = 'confirmed' AND reminder_24h_sent_at IS NULL;

-- Reminder job: find confirmed bookings needing 2h reminder.
CREATE INDEX idx_bookings_reminder_2h    ON bookings (appointment_start_at, reminder_2h_sent_at)
  WHERE status = 'confirmed' AND reminder_2h_sent_at IS NULL;

-- Review request job: find completed bookings needing review request.
CREATE INDEX idx_bookings_review_req     ON bookings (completed_at, review_requested_at)
  WHERE status = 'completed' AND review_requested_at IS NULL;

-- Reference lookup (patient enters booking reference in support).
CREATE INDEX idx_bookings_reference      ON bookings (booking_reference);

CREATE TRIGGER set_bookings_updated_at
  BEFORE UPDATE ON bookings
  FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();


-- ── TABLE: cancellations ──────────────────────────────────────
-- Every booking cancellation gets its own record.
-- Separate from bookings to keep the bookings table clean and
-- to support rich cancellation analytics (who cancels most? why?).
--
-- PRD Rule: if cancellation is within 2 hours of appointment,
-- it must be auto-flagged to admin. This is enforced by the
-- confirm_cancellation() function below.

CREATE TABLE cancellations (
  id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- The booking being cancelled.
  booking_id            UUID NOT NULL UNIQUE REFERENCES bookings(id)
                          ON DELETE RESTRICT,

  -- Denormalised for fast admin queries.
  patient_id            UUID NOT NULL REFERENCES patient_profiles(id)
                          ON DELETE RESTRICT,
  doctor_id             UUID NOT NULL REFERENCES doctor_profiles(id)
                          ON DELETE RESTRICT,
  clinic_id             UUID NOT NULL REFERENCES clinic_profiles(id)
                          ON DELETE RESTRICT,

  -- Who cancelled.
  cancelled_by          action_initiator NOT NULL,
  cancelled_by_user_id  UUID NOT NULL REFERENCES users(id)
                          ON DELETE RESTRICT,

  -- Why they cancelled.
  reason                cancellation_reason NOT NULL,

  -- Free-text explanation (mandatory for clinic/doctor, optional for patient).
  reason_detail         TEXT,

  -- When the cancellation happened.
  cancelled_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- The appointment time at point of cancellation (for 2h window check).
  appointment_was_at    TIMESTAMPTZ NOT NULL,

  -- How many minutes before the appointment was this cancelled?
  -- Computed and stored at cancellation time. Negative = after appointment.
  minutes_before_appointment INTEGER NOT NULL,

  -- Was this within the 2-hour window? (triggers admin flag)
  is_within_2h_window   BOOLEAN NOT NULL DEFAULT FALSE,

  -- Was a reschedule offered to the patient?
  reschedule_offered    BOOLEAN NOT NULL DEFAULT FALSE,
  reschedule_offered_at TIMESTAMPTZ,

  -- Did the patient accept the reschedule?
  reschedule_accepted   BOOLEAN,
  reschedule_accepted_at TIMESTAMPTZ,

  -- If rescheduled: the new booking that was created.
  new_booking_id        UUID REFERENCES bookings(id) ON DELETE SET NULL,

  -- Slot freed back to available at this time.
  slot_freed_at         TIMESTAMPTZ,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for cancellations.
CREATE INDEX idx_cancellations_booking      ON cancellations (booking_id);
CREATE INDEX idx_cancellations_patient      ON cancellations (patient_id);
CREATE INDEX idx_cancellations_doctor       ON cancellations (doctor_id);
CREATE INDEX idx_cancellations_clinic       ON cancellations (clinic_id);
CREATE INDEX idx_cancellations_initiator    ON cancellations (cancelled_by);

-- Admin: find all within-2h cancellations (the flagged ones).
CREATE INDEX idx_cancellations_2h_window    ON cancellations (is_within_2h_window, cancelled_at)
  WHERE is_within_2h_window = TRUE;

-- Analytics: cancellations by reason.
CREATE INDEX idx_cancellations_reason       ON cancellations (reason, cancelled_at);


-- ── TABLE: booking_audit_log ──────────────────────────────────
-- The immutable record of every action on every booking.
-- This table is APPEND-ONLY. No updates. No deletes. Ever.
-- It's your legal record, your customer support tool,
-- and your debugging history.
--
-- Design decision: store the full state snapshot in metadata JSONB.
-- This means even if we change our schema in the future, we can
-- still reconstruct what happened at any point in time.

CREATE TABLE booking_audit_log (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- The booking this log entry belongs to.
  booking_id    UUID NOT NULL REFERENCES bookings(id)
                  ON DELETE RESTRICT,

  -- What happened.
  action        audit_action NOT NULL,

  -- Who triggered this action.
  performed_by  action_initiator NOT NULL,

  -- The specific user who performed it (NULL for system actions).
  performed_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,

  -- Snapshot of the booking status at this point.
  booking_status_before booking_status,
  booking_status_after  booking_status,

  -- Any additional context about this action.
  -- Examples:
  --   For notification_sent: {"channel": "whatsapp", "template": "booking_confirmed", "phone": "+91..."}
  --   For payment_confirmed: {"gateway": "razorpay", "order_id": "order_XYZ", "amount_paise": 80000}
  --   For flag_raised: {"reason": "cancelled within 2 hours", "minutes_before": 87}
  metadata      JSONB DEFAULT '{}',

  -- Exact timestamp of this action (microsecond precision).
  occurred_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()

  -- No updated_at — this table is append-only.
);

-- Indexes for booking_audit_log.
-- Primary use: show full history of a booking (customer support).
CREATE INDEX idx_audit_booking_id    ON booking_audit_log (booking_id, occurred_at);

-- Admin dashboard: recent platform actions.
CREATE INDEX idx_audit_occurred_at   ON booking_audit_log (occurred_at DESC);

-- Find all actions by a specific user (for user activity review).
CREATE INDEX idx_audit_user_id       ON booking_audit_log (performed_by_user_id, occurred_at)
  WHERE performed_by_user_id IS NOT NULL;

-- Filter by action type (e.g., show all cancellations today).
CREATE INDEX idx_audit_action        ON booking_audit_log (action, occurred_at);


-- ── FUNCTION: confirm_booking() ───────────────────────────────
-- Called when a patient taps "Confirm Appointment".
-- Atomically:
--   1. Verifies the slot is still locked by this patient's session
--   2. Changes booking status from 'initiated' to 'confirmed'
--   3. Updates slot status from 'available' to 'booked'
--   4. Links booking_id on the slot
--   5. Writes audit log entry
-- All or nothing. If anything fails, everything rolls back.

CREATE OR REPLACE FUNCTION confirm_booking(
  p_booking_id  UUID,
  p_session_id  UUID   -- the user_sessions.id of the patient confirming
)
RETURNS BOOLEAN AS $$
DECLARE
  v_booking   bookings%ROWTYPE;
  v_slot      time_slots%ROWTYPE;
BEGIN
  -- Load and lock the booking row.
  SELECT * INTO v_booking
  FROM bookings
  WHERE id = p_booking_id AND status = 'initiated'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking % not found or not in initiated state', p_booking_id;
  END IF;

  -- Load and lock the slot row.
  SELECT * INTO v_slot
  FROM time_slots
  WHERE id = v_booking.slot_id
  FOR UPDATE;

  -- Verify the slot is still locked by THIS patient's session.
  -- If someone else locked it, or the lock expired, we reject.
  IF NOT v_slot.is_locked OR v_slot.locked_by_session != p_session_id THEN
    RAISE EXCEPTION 'Slot lock expired or does not belong to this session';
  END IF;

  -- Confirm the booking.
  UPDATE bookings
  SET
    status               = 'confirmed',
    confirmation_sent_at = NOW(),
    updated_at           = NOW()
  WHERE id = p_booking_id;

  -- Mark the slot as booked and clear the lock.
  UPDATE time_slots
  SET
    status            = 'booked',
    is_locked         = FALSE,
    locked_at         = NULL,
    locked_by_session = NULL,
    booking_id        = p_booking_id,
    updated_at        = NOW()
  WHERE id = v_booking.slot_id;

  -- Write audit log.
  INSERT INTO booking_audit_log (
    booking_id,
    action,
    performed_by,
    performed_by_user_id,
    booking_status_before,
    booking_status_after,
    metadata
  ) VALUES (
    p_booking_id,
    'booking_confirmed',
    'patient',
    -- Get user_id from the session
    (SELECT user_id FROM user_sessions WHERE id = p_session_id),
    'initiated',
    'confirmed',
    jsonb_build_object(
      'session_id', p_session_id,
      'slot_id', v_booking.slot_id,
      'appointment_at', v_booking.appointment_start_at
    )
  );

  -- Increment patient's total_bookings counter.
  UPDATE patient_profiles
  SET
    total_bookings = total_bookings + 1,
    updated_at     = NOW()
  WHERE id = v_booking.patient_id;

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;


-- ── FUNCTION: cancel_booking() ───────────────────────────────
-- Called when any party cancels a booking.
-- Atomically:
--   1. Updates booking status to 'cancelled'
--   2. Frees the time slot back to 'available'
--   3. Creates a cancellations record
--   4. Checks the 2-hour window and flags if needed
--   5. Writes audit log
--   6. Decrements patient booking counter

CREATE OR REPLACE FUNCTION cancel_booking(
  p_booking_id        UUID,
  p_cancelled_by      action_initiator,
  p_user_id           UUID,
  p_reason            cancellation_reason,
  p_reason_detail     TEXT DEFAULT NULL
)
RETURNS UUID AS $$  -- returns cancellation id
DECLARE
  v_booking             bookings%ROWTYPE;
  v_minutes_before      INTEGER;
  v_is_within_2h        BOOLEAN;
  v_cancellation_id     UUID;
  v_flag_reason         TEXT;
BEGIN
  -- Load and lock the booking.
  SELECT * INTO v_booking
  FROM bookings
  WHERE id = p_booking_id
    AND status IN ('confirmed', 'initiated')
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Booking % cannot be cancelled (not found or wrong status)', p_booking_id;
  END IF;

  -- Calculate how many minutes before appointment this cancellation is.
  v_minutes_before := EXTRACT(
    EPOCH FROM (v_booking.appointment_start_at - NOW())
  )::INTEGER / 60;

  -- PRD Rule: flag if cancelled within 120 minutes (2 hours).
  v_is_within_2h := v_minutes_before < 120 AND v_minutes_before > 0;

  -- Create the flag reason text if applicable.
  IF v_is_within_2h THEN
    v_flag_reason := format(
      'Cancellation by %s with %s minutes before appointment',
      p_cancelled_by::TEXT,
      v_minutes_before
    );
  END IF;

  -- Update the booking status.
  UPDATE bookings
  SET
    status        = 'cancelled',
    is_flagged    = v_is_within_2h,
    flag_reason   = v_flag_reason,
    flagged_at    = CASE WHEN v_is_within_2h THEN NOW() ELSE NULL END,
    updated_at    = NOW()
  WHERE id = p_booking_id;

  -- Free the slot back to available.
  -- (Only if the appointment hasn't passed yet.)
  IF v_booking.appointment_start_at > NOW() THEN
    UPDATE time_slots
    SET
      status      = 'available',
      booking_id  = NULL,
      is_locked   = FALSE,
      locked_at   = NULL,
      locked_by_session = NULL,
      updated_at  = NOW()
    WHERE id = v_booking.slot_id;
  END IF;

  -- Create cancellation record.
  INSERT INTO cancellations (
    booking_id,
    patient_id,
    doctor_id,
    clinic_id,
    cancelled_by,
    cancelled_by_user_id,
    reason,
    reason_detail,
    appointment_was_at,
    minutes_before_appointment,
    is_within_2h_window,
    slot_freed_at
  ) VALUES (
    p_booking_id,
    v_booking.patient_id,
    v_booking.doctor_id,
    v_booking.clinic_id,
    p_cancelled_by,
    p_user_id,
    p_reason,
    p_reason_detail,
    v_booking.appointment_start_at,
    v_minutes_before,
    v_is_within_2h,
    CASE WHEN v_booking.appointment_start_at > NOW() THEN NOW() ELSE NULL END
  )
  RETURNING id INTO v_cancellation_id;

  -- Write audit log.
  INSERT INTO booking_audit_log (
    booking_id,
    action,
    performed_by,
    performed_by_user_id,
    booking_status_before,
    booking_status_after,
    metadata
  ) VALUES (
    p_booking_id,
    'booking_cancelled',
    p_cancelled_by,
    p_user_id,
    'confirmed',
    'cancelled',
    jsonb_build_object(
      'reason',                p_reason,
      'reason_detail',         p_reason_detail,
      'minutes_before',        v_minutes_before,
      'is_within_2h_window',   v_is_within_2h,
      'cancellation_id',       v_cancellation_id,
      'is_flagged',            v_is_within_2h
    )
  );

  -- Decrement patient's booking counter.
  UPDATE patient_profiles
  SET
    total_bookings = GREATEST(total_bookings - 1, 0),
    updated_at     = NOW()
  WHERE id = v_booking.patient_id;

  RETURN v_cancellation_id;
END;
$$ LANGUAGE plpgsql;


-- ── FUNCTION: reschedule_booking() ───────────────────────────
-- Called when any party reschedules to a new slot.
-- Atomically:
--   1. Cancels the original booking (marks as 'rescheduled')
--   2. Frees the original slot
--   3. Locks the new slot
--   4. Creates a new booking for the new slot
--   5. Links old and new bookings together
--   6. Writes audit log for both

CREATE OR REPLACE FUNCTION reschedule_booking(
  p_old_booking_id    UUID,
  p_new_slot_id       UUID,
  p_rescheduled_by    action_initiator,
  p_user_id           UUID,
  p_session_id        UUID
)
RETURNS UUID AS $$  -- returns new booking id
DECLARE
  v_old_booking   bookings%ROWTYPE;
  v_new_slot      time_slots%ROWTYPE;
  v_new_booking_id UUID;
  v_new_reference  VARCHAR(20);
BEGIN
  -- Load and lock the original booking.
  SELECT * INTO v_old_booking
  FROM bookings
  WHERE id = p_old_booking_id AND status = 'confirmed'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Original booking % not found or not confirmed', p_old_booking_id;
  END IF;

  -- Load and lock the new slot.
  SELECT * INTO v_new_slot
  FROM time_slots
  WHERE id = p_new_slot_id AND status = 'available'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'New slot % not available', p_new_slot_id;
  END IF;

  -- Verify new slot is for the same doctor (can change clinic location).
  IF v_new_slot.doctor_id != v_old_booking.doctor_id THEN
    RAISE EXCEPTION 'Cannot reschedule to a different doctor';
  END IF;

  -- Generate a new booking reference.
  v_new_reference := 'MB-' || LPAD(
    FLOOR(RANDOM() * 99999)::TEXT, 5, '0'
  );

  -- Create the new booking in 'confirmed' state directly.
  INSERT INTO bookings (
    booking_reference,
    patient_id,
    doctor_id,
    clinic_id,
    slot_id,
    appointment_date,
    appointment_start_at,
    appointment_end_at,
    status,
    reason_for_visit,
    payment_method,
    payment_status,
    fee_paise,
    rescheduled_from_id,
    confirmation_sent_at,
    booking_source
  ) VALUES (
    v_new_reference,
    v_old_booking.patient_id,
    v_new_slot.doctor_id,
    v_new_slot.clinic_id,
    p_new_slot_id,
    v_new_slot.slot_date,
    v_new_slot.slot_start_at,
    v_new_slot.slot_end_at,
    'confirmed',
    v_old_booking.reason_for_visit,
    v_old_booking.payment_method,
    v_old_booking.payment_status,
    v_old_booking.fee_paise,
    p_old_booking_id,
    NOW(),
    v_old_booking.booking_source
  )
  RETURNING id INTO v_new_booking_id;

  -- Mark new slot as booked.
  UPDATE time_slots
  SET
    status     = 'booked',
    booking_id = v_new_booking_id,
    is_locked  = FALSE,
    updated_at = NOW()
  WHERE id = p_new_slot_id;

  -- Mark old booking as rescheduled, link to new booking.
  UPDATE bookings
  SET
    status            = 'rescheduled',
    rescheduled_to_id = v_new_booking_id,
    updated_at        = NOW()
  WHERE id = p_old_booking_id;

  -- Free the old slot.
  UPDATE time_slots
  SET
    status     = 'available',
    booking_id = NULL,
    updated_at = NOW()
  WHERE id = v_old_booking.slot_id
    AND v_old_booking.appointment_start_at > NOW();

  -- Audit log: old booking rescheduled.
  INSERT INTO booking_audit_log (
    booking_id, action, performed_by, performed_by_user_id,
    booking_status_before, booking_status_after, metadata
  ) VALUES (
    p_old_booking_id, 'booking_rescheduled', p_rescheduled_by, p_user_id,
    'confirmed', 'rescheduled',
    jsonb_build_object('new_booking_id', v_new_booking_id, 'new_slot_id', p_new_slot_id)
  );

  -- Audit log: new booking confirmed.
  INSERT INTO booking_audit_log (
    booking_id, action, performed_by, performed_by_user_id,
    booking_status_before, booking_status_after, metadata
  ) VALUES (
    v_new_booking_id, 'booking_confirmed', p_rescheduled_by, p_user_id,
    NULL, 'confirmed',
    jsonb_build_object(
      'rescheduled_from', p_old_booking_id,
      'new_slot_date', v_new_slot.slot_date,
      'new_slot_time', v_new_slot.slot_start_time
    )
  );

  RETURN v_new_booking_id;
END;
$$ LANGUAGE plpgsql;


-- ── FUNCTION: complete_booking() ─────────────────────────────
-- Called by clinic when patient is marked as 'Seen/Done'.
-- Also called automatically by a background job 30 minutes after
-- appointment end time if clinic hasn't marked it.

CREATE OR REPLACE FUNCTION complete_booking(
  p_booking_id    UUID,
  p_completed_by  UUID  -- user_id of clinic staff or NULL for system
)
RETURNS BOOLEAN AS $$
DECLARE
  v_booking bookings%ROWTYPE;
BEGIN
  SELECT * INTO v_booking
  FROM bookings
  WHERE id = p_booking_id AND status = 'confirmed'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN FALSE;
  END IF;

  UPDATE bookings
  SET
    status        = 'completed',
    completed_at  = NOW(),
    completed_by  = p_completed_by,
    updated_at    = NOW()
  WHERE id = p_booking_id;

  -- Increment doctor's total appointments counter.
  UPDATE doctor_profiles
  SET
    total_appointments = total_appointments + 1,
    updated_at         = NOW()
  WHERE id = v_booking.doctor_id;

  -- Write audit log.
  INSERT INTO booking_audit_log (
    booking_id, action, performed_by, performed_by_user_id,
    booking_status_before, booking_status_after, metadata
  ) VALUES (
    p_booking_id,
    'booking_completed',
    CASE WHEN p_completed_by IS NULL THEN 'system' ELSE 'clinic' END,
    p_completed_by,
    'confirmed', 'completed',
    jsonb_build_object('completed_at', NOW(), 'auto_completed', p_completed_by IS NULL)
  );

  RETURN TRUE;
END;
$$ LANGUAGE plpgsql;


-- ── SCHEDULED JOB NOTES ───────────────────────────────────────
-- Add these to your job scheduler (pg_cron / EventBridge):
--
-- Job 5: Auto-complete appointments (runs every 30 minutes)
--   Complete confirmed bookings whose end time passed 30+ minutes ago.
--   SELECT complete_booking(id, NULL)
--   FROM bookings
--   WHERE status = 'confirmed'
--     AND appointment_end_at < NOW() - INTERVAL '30 minutes';
--
-- Job 6: Send 24h reminders (runs every hour)
--   UPDATE bookings SET reminder_24h_sent_at = NOW()
--   WHERE status = 'confirmed'
--     AND reminder_24h_sent_at IS NULL
--     AND appointment_start_at BETWEEN NOW() + INTERVAL '23 hours'
--                                   AND NOW() + INTERVAL '25 hours';
--   (Application layer then sends the actual WhatsApp/SMS)
--
-- Job 7: Send 2h reminders (runs every 15 minutes)
--   UPDATE bookings SET reminder_2h_sent_at = NOW()
--   WHERE status = 'confirmed'
--     AND reminder_2h_sent_at IS NULL
--     AND appointment_start_at BETWEEN NOW() + INTERVAL '1h 45m'
--                                   AND NOW() + INTERVAL '2h 15m';
--
-- Job 8: Request post-visit reviews (runs every hour)
--   UPDATE bookings SET review_requested_at = NOW()
--   WHERE status = 'completed'
--     AND review_requested_at IS NULL
--     AND completed_at < NOW() - INTERVAL '1 hour';
--   (Application layer sends WhatsApp review request)
--
-- Job 9: Auto no-show (runs every hour)
--   Mark confirmed bookings as no_show if appointment time passed
--   and clinic never marked them as completed or cancelled.
--   UPDATE bookings SET status = 'no_show', no_show_recorded_at = NOW(),
--                       no_show_recorded_by = NULL
--   WHERE status = 'confirmed'
--     AND appointment_end_at < NOW() - INTERVAL '2 hours';


-- ── BOOKING REFERENCE GENERATION NOTE ────────────────────────
-- Booking references (e.g., MB-30841) are generated in application
-- code — not in SQL — to avoid collisions and allow custom formats.
-- Recommended approach:
--   prefix = 'MB'
--   number = random 5-digit number
--   check uniqueness before insert
--   retry if collision (extremely rare)
-- Format: MB-XXXXX (e.g., MB-30841, MB-00042)


-- ============================================================
--  END OF PHASE 4: BOOKINGS
--
--  Tables created:
--    bookings              — core booking record, full lifecycle
--    cancellations         — rich cancellation records per booking
--    booking_audit_log     — immutable append-only action history
--
--  Functions created:
--    confirm_booking()     — atomic slot lock + booking confirmation
--    cancel_booking()      — atomic cancellation + slot free + 2h flag check
--    reschedule_booking()  — atomic old cancel + new booking creation
--    complete_booking()    — marks appointment as done, triggers review req
--
--  Enums created:
--    booking_status        — 6 states: initiated→confirmed→completed/cancelled/rescheduled/no_show
--    payment_method        — pay_at_clinic | upi_online | card_online
--    payment_status        — not_applicable | pending | paid | failed | refunded
--    action_initiator      — patient | doctor | clinic | platform_admin | system
--    cancellation_reason   — 13 specific reasons across all parties
--    audit_action          — 16 action types for full audit trail
--
--  Key design decisions:
--    - Bookings are NEVER deleted — only status changes
--    - Audit log is APPEND-ONLY — no updates, no deletes, ever
--    - Cancellations are their own entity (rich analytics + admin flagging)
--    - Reschedule = cancel old + create new (full history preserved)
--    - 2-hour cancellation window auto-flags to admin (PRD rule enforced in DB)
--    - Fees stored at booking time in paise (historical record, never changes)
--    - All functions are atomic — all or nothing, no partial states
--    - 9 scheduled jobs keep the booking lifecycle running automatically
--
--  Next: Phase 5 — Reviews & Ratings + Notifications Log + Payments
-- ============================================================
